[package]
name = "collections"
version = "0.1.0"
authors = ["rashid semenov <rashid.semenov@absa.co.za>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
